// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ColumnVideo: typeof import('./src/components/columnVideo.vue')['default']
    CommentRely: typeof import('./src/components/commentRely.vue')['default']
    Comments: typeof import('./src/components/comments.vue')['default']
    copy: typeof import('./src/components/columnVideo copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Fold: typeof import('./src/components/fold.vue')['default']
    Load: typeof import('./src/components/load.vue')['default']
    LoadMore: typeof import('./src/components/loadMore.vue')['default']
    PlayVideo: typeof import('./src/components/playVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowVideo: typeof import('./src/components/rowVideo.vue')['default']
    TopButton: typeof import('./src/components/topButton.vue')['default']
    TopList: typeof import('./src/components/topList.vue')['default']
    VideoTags: typeof import('./src/components/videoTags.vue')['default']
  }
}
