// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404View: typeof import('./src/components/404View.vue')['default']
    Column: typeof import('./src/components/column.vue')['default']
    ColumnVideo: typeof import('./src/components/columnVideo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    LoginView: typeof import('./src/components/LoginView.vue')['default']
    PlayVideo: typeof import('./src/components/playVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopButton: typeof import('./src/components/topButton.vue')['default']
    TopList: typeof import('./src/components/topList.vue')['default']
  }
}
